/* Generated By:JavaCC: Do not edit this line. MotivationParserConstants.java */
package com.github.angerona.fw.motivation.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MotivationParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int KEYWORD = 7;
  /** RegularExpression Id. */
  int NEG = 8;
  /** RegularExpression Id. */
  int OPEN = 9;
  /** RegularExpression Id. */
  int CLOSE = 10;
  /** RegularExpression Id. */
  int KOMMA = 11;
  /** RegularExpression Id. */
  int OPAR = 12;
  /** RegularExpression Id. */
  int CPAR = 13;
  /** RegularExpression Id. */
  int DIV = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<NUMBER>",
    "<KEYWORD>",
    "\"-\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\";\"",
  };

}
