/* Generated By:JavaCC: Do not edit this line. BeliefbaseSetParserConstants.java */
package com.github.angerona.fw.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BeliefbaseSetParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int POINTER = 5;
  /** RegularExpression Id. */
  int KW_WORLD = 6;
  /** RegularExpression Id. */
  int KW_VIEW = 7;
  /** RegularExpression Id. */
  int TEXT_CHAR = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LOGIC = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"->\"",
    "\"world\"",
    "\"view\"",
    "<TEXT_CHAR>",
    "\"{\"",
    "\"}\"",
    "<token of kind 11>",
  };

}
