/* Generated By:JavaCC: Do not edit this line. SecretParserConstants.java */
package com.github.angerona.fw.am.secrecy.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SecretParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TEXT_CHAR = 5;
  /** RegularExpression Id. */
  int LPARANTHESS = 6;
  /** RegularExpression Id. */
  int RPARANTHESS = 7;
  /** RegularExpression Id. */
  int LBRACE = 8;
  /** RegularExpression Id. */
  int RBRACE = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int EQUAL = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int LOGIC_UNARY_SYMBOL = 13;
  /** RegularExpression Id. */
  int LOGIC_BINARY_SYMBOL = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<TEXT_CHAR>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\",\"",
    "<LOGIC_UNARY_SYMBOL>",
    "<LOGIC_BINARY_SYMBOL>",
  };

}
