/* Generated By:JavaCC: Do not edit this line. ASMLParserConstants.java */
package com.github.kreaturesfw.core.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ASMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHARACTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int VAR = 7;
  /** RegularExpression Id. */
  int DOT = 8;
  /** RegularExpression Id. */
  int COMPARE_OPERATOR = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<CHARACTER>",
    "<DIGIT>",
    "\"$\"",
    "\".\"",
    "<COMPARE_OPERATOR>",
  };

}
