/* Generated By:JavaCC: Do not edit this line. KnowhowParserConstants.java */
package com.github.angerona.knowhow.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KnowhowParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int DOT = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int CHAR = 12;
  /** RegularExpression Id. */
  int UCHAR = 13;
  /** RegularExpression Id. */
  int BLANK = 14;
  /** RegularExpression Id. */
  int TEXT = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<DIGIT>",
    "<CHAR>",
    "<UCHAR>",
    "\"_\"",
    "<TEXT>",
  };

}
