/* Generated By:JavaCC: Do not edit this line. FolParserBConstants.java */
package net.sf.tweety.logics.firstorderlogic.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FolParserBConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORALL = 6;
  /** RegularExpression Id. */
  int EXISTS = 7;
  /** RegularExpression Id. */
  int TYPE = 8;
  /** RegularExpression Id. */
  int DDOT = 9;
  /** RegularExpression Id. */
  int EQUAL = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int TAUTOLOGY = 14;
  /** RegularExpression Id. */
  int CONTRADICTION = 15;
  /** RegularExpression Id. */
  int LBRA = 16;
  /** RegularExpression Id. */
  int RBRA = 17;
  /** RegularExpression Id. */
  int SQLBRA = 18;
  /** RegularExpression Id. */
  int SQRBRA = 19;
  /** RegularExpression Id. */
  int CURLBRA = 20;
  /** RegularExpression Id. */
  int CURRBRA = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int LCHAR = 24;
  /** RegularExpression Id. */
  int UCHAR = 25;
  /** RegularExpression Id. */
  int SYMBOL = 26;
  /** RegularExpression Id. */
  int CONSTANT = 27;
  /** RegularExpression Id. */
  int VARIABLE = 28;
  /** RegularExpression Id. */
  int BLANK = 29;
  /** RegularExpression Id. */
  int COMMA = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"forall\"",
    "\"exist\"",
    "\"type\"",
    "\":\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"-\"",
    "\"+\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<DIGIT>",
    "<NUMBER>",
    "<LCHAR>",
    "<UCHAR>",
    "<SYMBOL>",
    "<CONSTANT>",
    "<VARIABLE>",
    "\"_\"",
    "\",\"",
  };

}
